# -*- coding: utf-8 -*-
"""HW3 :Books Managing System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UtOeOQhpIcajQy0sUnafvlOGbhida8Pn
"""

import math

books = []

def add_book(name, price, quantity):
    book = {}
    book['name'] = name
    book['price'] = price
    book['quantity'] = quantity
    books.append(book)
    print(f"\n書籍'{name}'已成功添加到庫存!\n")

def del_book(name):
    for index in range(len(books)):
        if books[index]['name'] == name:
            del books[index]
            break
    print(f"\n書籍'{name}'已成功從庫存中移除!\n")

def find_book(name):
    found = False
    for index in range(len(books)):
        if books[index]['name'] == name:
            print(f"\n書名: {name} \n價格: {books[index]['price']} \n庫存: {books[index]['quantity']} \n")
            found = True
    if found == False:
        print(f"\n找不到名為'{name}'的書!\n")

def show_quantity():
    print("\n當前庫存: ")
    for book in books:
        print(f"書名: {book['name']}, 價格:{book['price']}, 庫存: {book['quantity']}本")
    print()

def modify_quantity(name, new_quantity):
     for index in range(len(books)):
        if books[index]['name'] == name:
            books[index]['quantity'] = new_quantity
            print(f"\n書籍'{name}'的庫存已成功更新為 {new_quantity} 本!\n")

def add_order(name, quantity):
    order = {}
    order['name'] = name
    order['quantity'] = quantity
    order_list.append(order)


def check_quantity(name, quantity):
    for item in order_list:
        for book in books:
            if item['name'] == book['name']:
                if item['quantity'] <= book['quantity']:
                    return True
                else:
                    return False

def order():
    total_price = 0
    for item in order_list:
        for book in books:
            if item['name'] == book['name']:
                total_price += book['price'] * item['quantity']
                discount(total_price)

def discount(total_price):
    if total_price >= 1000:
        discount = 0.85
        total_price *= discount
        print(f"\n因為您的消費金額已經達到1000元, 所以享獲85折的折扣! \n折扣後的金額為: {math.floor(total_price)}元\n")
    else:
        print(f"\n您訂購的總金額為: {total_price}\n")


while True:

    print("""請選擇你要做的操作:
    1.添加書籍
    2.刪除書籍
    3.尋找書籍
    4.顯示庫存
    5.更新庫存
    6.訂購書籍
    7.退出
    """)

    select_service = int(input("請輸入數字(1~7): "))
    if select_service == 1:
        book_name = input("請輸入想要加入的書籍名稱: ")
        book_price = int(input("請輸入該書籍的價格: "))
        book_quantity = int(input("請輸入該書籍的數量: "))
        print()
        add_book(book_name, book_price, book_quantity)

    elif select_service == 2:
        book_name = input("請輸入想要刪除的書籍名稱:")
        print()
        del_book(book_name)

    elif select_service == 3:
        book_name = input("請輸入想要查詢的書籍名稱:")
        find_book(book_name)

    elif select_service == 4:
        show_quantity()

    elif select_service == 5:
        book_name = input("請輸入想更動庫存的書籍名稱:")
        new_quantity = int(input("請輸入想要變更的數量:"))
        modify_quantity(book_name, new_quantity)

    elif select_service == 6:
        order_count = int(input("輸入想要訂購的書種數量: "))
        out_of_book = False
        for i in range(order_count):
            order_list = []
            book_name = input("請輸入想購買的書籍名稱: ")
            book_quantity = int(input("請輸入想要購買的數量: "))
            add_order(book_name, book_quantity)
            check = check_quantity(book_name, book_quantity)
            if check == False:
                print(f"\n抱歉, {book_name}沒有這麼多庫存!\n")
                out_of_book = True
                break

        if out_of_book != True:
            order()

    elif select_service == 7:
        print("\n謝謝您的使用!")
        break